on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment"
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        run: echo "Deploy the app to ${{ inputs.environment }}"